/*					=== CREATE DATABASE ===      		      */ 
DROP DATABASE IF EXISTS Fresher;
CREATE DATABASE Fresher;
USE Fresher;

/*					=== CREATE TABLE ===						*/	
DROP TABLE IF EXISTS Trainee;
CREATE TABLE Trainee (
    Trainee_ID 				MEDIUMINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Full_Name 				NVARCHAR(100) NOT NULL,
    Birth_Date				DATETIME DEFAULT NOW() NOT NULL,
    Gender 					ENUM('MALE', 'FEMALE', 'UNKNOWN') NOT NULL,
    ET_IQ 					TINYINT UNSIGNED NOT NULL,
    ET_Gmath 				TINYINT UNSIGNED NOT NULL,
    ET_English 				TINYINT UNSIGNED NOT NULL,
    Training_Class 			TINYINT UNSIGNED NOT NULL,
    Evalution_Notes 		NVARCHAR(100),
    VTI_Account				SMALLINT NOT NULL UNIQUE KEY
);

INSERT INTO fresher 
(
	
);